# Generated by Django 4.1.6 on 2023-02-08 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=220, null=True)),
                ('First_Name', models.TextField(blank=True, null=True)),
                ('Last_Name', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('height', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('location', models.CharField(blank=True, max_length=220, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('height', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChampionLeague',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Afcon',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Baseball',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Bundesliga',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Europa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Formula1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Laliga',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='NBA',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='NFL',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Worldcup',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='clubimage',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AfconLeague',
        ),
        migrations.DeleteModel(
            name='Baseball',
        ),
        migrations.DeleteModel(
            name='Bundesliga',
        ),
        migrations.DeleteModel(
            name='EuropaLeague',
        ),
        migrations.DeleteModel(
            name='Formula1',
        ),
        migrations.DeleteModel(
            name='Laliga',
        ),
        migrations.DeleteModel(
            name='NBA',
        ),
        migrations.DeleteModel(
            name='NFL',
        ),
        migrations.DeleteModel(
            name='Worldcup',
        ),
    ]
